### PR TITLE
Updated CSS naming

### PR DESCRIPTION
**Pull request by speakerbug**
This PR updates the CSS names to match typical naming conventions.

### CODE REVIEW

**Review by tadhunt — CHANGES_REQUESTED** [review]
Hi Henry, from the diff it looks like your editor partially reformatted the file (tabs to spaces), mixing syntax with semantic changes.  I'd expect the diff to only show the semantic changes (lines where the class names change).

**Comment by tadhunt** [comment]
I'm learning the tools, and I think I can do a squashed merge once the syntax changes are backed out, so you can do that in this same PR if you like.

**Comment by speakerbug** [comment]
Yep, you're right. Totally didn't notice that. Just committed again so you can squash and merge.

**Comment by tadhunt** [comment]
I just tested this change and it appears to work fine.
LGTM, I'll merge it momentarily.

**Review by tadhunt — APPROVED** [review]

**Pull request merged**
